on:
  push:
    branches:
      - main

name: ðŸš€ Deploy Website via FTP
jobs:
  web-deploy:
    name: ðŸš€ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: ðŸ“‚ Push Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c # v4.3.4
        with:
          server: ftp.absolutehealing.ie
          username: ${{ secrets.ABSOLUTE_FTP_USERNAME }}
          password: ${{ secrets.ABSOLUTE_FTP_PASSWORD }}

          local-dir: ./
          server-dir: public_html/
